services:
  frontend:
    container_name: frontend
    build: ./todoApp/
    volumes:
      - shared-volume:/app/frontend

  backend:
    container_name: backend
    build: ./todoBackend/
    volumes:
      - shared-volume:/app/backend
    depends_on:
      - frontend
    ports:
      - "80:8080"
volumes:
  shared-volume:
